blank_issues_enabled: false
contact_links:
  - name: Descargas de Committee of Zero
    url: https://github.com/CommitteeOfZero/chn-patch/releases
    about: Obtén aquí el Overhaul Patch oficial; es un requisito externo.
